### ISSUE TITLE
Improved Bourgain embedding

### ISSUE THREAD

**Issue by denkorzh** [orgesleka/bourgain_embedding#1]
A recent [paper on BourGAN](http://papers.nips.cc/paper/7495-bourgan-generative-networks-with-metric-embeddings) at NeurIPS 2018 also mentions Improved Bourgain embedding that shrinks the dimensionality of the embedding space to O(log n) and provides an algorithm in Appendix A.

**Comment by orgesleka** [comment]
@denkorzh: Thank your for the hint. I will have a look at it.

**Comment by orgesleka** [comment]
I found the source code here from the authors of the article:
https://github.com/a554b554/BourGAN/blob/master/src/bourgan/embed.py
You might want to have a look at it.
I will close this issue.
